language: node_js
sudo: required
node_js:
  - '8'
services:
  - docker

install:
  - echo 'no install required'
script:
  - echo 'no script required'

before_deploy: docker-compose up --build
deploy:
  - provider: s3
    access_key_id: $TEST_AWS_ACCESS_KEY_ID
    secret_access_key: $TEST_AWS_SECRET_ACCESS_KEY
    bucket: docs-test.thingsinmotion.io
    acl: public_read
    region: ap-southeast-2
    skip_cleanup: true
    local-dir: build
    on:
      branch: "master"
  - provider: s3
    access_key_id: $PROD_AWS_ACCESS_KEY_ID
    secret_access_key: $PROD_AWS_SECRET_ACCESS_KEY
    bucket: docs.thingsinmotion.io
    acl: public_read
    region: ap-southeast-2
    skip_cleanup: true
    local-dir: build
    on:
      tags: true